# Generated by Django 3.2.10 on 2022-02-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(max_length=10)),
                ('orderTime', models.IntegerField(max_length=15)),
                ('skuId', models.IntegerField(max_length=10)),
                ('userId', models.IntegerField(max_length=10)),
                ('status', models.IntegerField(max_length=10)),
                ('price', models.FloatField(max_length=15)),
                ('ordpayerTime', models.FloatField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
