# Generated by Django 3.2.10 on 2022-02-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbModel', '0002_auto_20220222_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ordpayerTime',
            new_name='pay',
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='skuId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
